name: Deploy with Docker Compose

on:
  workflow_run:
    workflows: ["Build and Push Backend Docker Image", "Build and Push Frontend Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull and run Docker containers with Docker Compose
      run: |
        docker-compose pull
        docker-compose up -d
